[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn project.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
DJANGO_SETTINGS_MODULE = "project.settings" 