[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
startCommand = "bash railway-start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
DJANGO_SETTINGS_MODULE = "project.settings"
