services:
  - type: web
    name: job-board
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jobsproject.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
