# Generated by Django 5.1.1 on 2025-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_password_token',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
