# Generated by Django 5.1.7 on 2025-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_responsibilities_alter_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
