# Generated by Django 5.1.7 on 2025-06-01 18:03

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_responsibilities_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.image_upload),
        ),
    ]
